IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Tickets' AND xtype='U')
  CREATE TABLE Tickets
  (
    id int NOT NULL UNIQUE,
    title nvarchar(1024),
    additionalRecipient nvarchar(256),
    assignedTo nvarchar(256),
    customer nvarchar(256),
    creationType nvarchar(32),
    dept nvarchar(6),
    description nvarchar(max),
    ip nvarchar(128),
    priority nvarchar(10),
    referenceNumber nvarchar(128),
    referenceUrl nvarchar(1024),
    requestType nvarchar(32),
    secondaryAssignee nvarchar(256),
    securityCategory nvarchar(64),
    securityResults nvarchar(20),
    securitySystems nvarchar(512),
    serviceType nvarchar(256),
    status nvarchar(10),
    subTopic nvarchar(128),
    topic nvarchar(128),
    urgency nvarchar(10),
    startDate date,
    completed date,
    dueDate dateTime,
    createdBy nvarchar(256),
    created datetime,
    modifiedBy nvarchar(256),
    modified datetime,
    CONSTRAINT PK_tickets PRIMARY KEY CLUSTERED (id)
  )
